
/**************************************************************
 *	
 *	Blaster, 8 bit, 11025Hz,
 *	1 channel, 13406 bytes/channel
 *	Total Size: 1 * 13406 + 4 (header) = 13450 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/Blaster.wav
 *	Time-stamp: Mon Apr 15 10:29:00 2019
 *	
 **************************************************************/

#ifndef __BLASTERH__
#define __BLASTERH__

#define BLASTERFREQ 11025
#define BLASTERLEN 13406

extern const unsigned char Blaster[13406];

#endif /* __BLASTERH__ */
