
/**************************************************************
 *	
 *	CloudlandRegion, 8 bit, 11025Hz,
 *	1 channel, 917856 bytes/channel
 *	Total Size: 1 * 917856 + 4 (header) = 917900 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/CloudlandRegion.wav
 *	Time-stamp: Mon Apr 15 10:29:24 2019
 *	
 **************************************************************/

#ifndef __CLOUDLANDREGIONH__
#define __CLOUDLANDREGIONH__

#define CLOUDLANDREGIONFREQ 11025
#define CLOUDLANDREGIONLEN 917856

extern const unsigned char CloudlandRegion[917856];

#endif /* __CLOUDLANDREGIONH__ */
