
/**************************************************************
 *	
 *	CollisionBody, 8 bit, 11025Hz,
 *	1 channel, 10231 bytes/channel
 *	Total Size: 1 * 10231 + 4 (header) = 10275 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/CollisionBody.wav
 *	Time-stamp: Mon Apr 15 10:29:43 2019
 *	
 **************************************************************/

#ifndef __COLLISIONBODYH__
#define __COLLISIONBODYH__

#define COLLISIONBODYFREQ 11025
#define COLLISIONBODYLEN 10231

extern const unsigned char CollisionBody[10231];

#endif /* __COLLISIONBODYH__ */
