
/**************************************************************
 *	
 *	Levels, 8 bit, 11025Hz,
 *	1 channel, 2056032 bytes/channel
 *	Total Size: 1 * 2056032 + 4 (header) = 2056076 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/Levels.wav
 *	Time-stamp: Mon Apr 15 10:29:59 2019
 *	
 **************************************************************/

#ifndef __LEVELSH__
#define __LEVELSH__

#define LEVELSFREQ 11025
#define LEVELSLEN 2056032

extern const unsigned char Levels[2056032];

#endif /* __LEVELSH__ */
