
/**************************************************************
 *	
 *	MenuNav, 8 bit, 11025Hz,
 *	1 channel, 3646 bytes/channel
 *	Total Size: 1 * 3646 + 4 (header) = 3690 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/MenuNav.wav
 *	Time-stamp: Mon Apr 15 10:31:09 2019
 *	
 **************************************************************/

#ifndef __MENUNAVH__
#define __MENUNAVH__

#define MENUNAVFREQ 11025
#define MENUNAVLEN 3646

extern const unsigned char MenuNav[3646];

#endif /* __MENUNAVH__ */
