
/**************************************************************
 *	
 *	MeufordReset, 8 bit, 11025Hz,
 *	1 channel, 18698 bytes/channel
 *	Total Size: 1 * 18698 + 4 (header) = 18742 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/MeufordReset.wav
 *	Time-stamp: Mon Apr 15 10:31:27 2019
 *	
 **************************************************************/

#ifndef __MEUFORDRESETH__
#define __MEUFORDRESETH__

#define MEUFORDRESETFREQ 11025
#define MEUFORDRESETLEN 18698

extern const unsigned char MeufordReset[18698];

#endif /* __MEUFORDRESETH__ */
