
/**************************************************************
 *	
 *	MotherMainTheme, 8 bit, 11025Hz,
 *	1 channel, 392544 bytes/channel
 *	Total Size: 1 * 392544 + 4 (header) = 392588 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/MotherMainTheme.wav
 *	Time-stamp: Mon Apr 15 10:31:40 2019
 *	
 **************************************************************/

#ifndef __MOTHERMAINTHEMEH__
#define __MOTHERMAINTHEMEH__

#define MOTHERMAINTHEMEFREQ 11025
#define MOTHERMAINTHEMELEN 392544

extern const unsigned char MotherMainTheme[392544];

#endif /* __MOTHERMAINTHEMEH__ */
