
/**************************************************************
 *	
 *	MusselReset, 8 bit, 11025Hz,
 *	1 channel, 23755 bytes/channel
 *	Total Size: 1 * 23755 + 4 (header) = 23799 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/MusselReset.wav
 *	Time-stamp: Mon Apr 15 10:31:53 2019
 *	
 **************************************************************/

#ifndef __MUSSELRESETH__
#define __MUSSELRESETH__

#define MUSSELRESETFREQ 11025
#define MUSSELRESETLEN 23755

extern const unsigned char MusselReset[23755];

#endif /* __MUSSELRESETH__ */
