
/**************************************************************
 *	
 *	Scare, 8 bit, 11025Hz,
 *	1 channel, 491904 bytes/channel
 *	Total Size: 1 * 491904 + 4 (header) = 491948 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/Scare.wav
 *	Time-stamp: Mon Apr 15 10:32:05 2019
 *	
 **************************************************************/

#ifndef __SCAREH__
#define __SCAREH__

#define SCAREFREQ 11025
#define SCARELEN 491904

extern const unsigned char Scare[491904];

#endif /* __SCAREH__ */
