
/**************************************************************
 *	
 *	Scifi, 8 bit, 11025Hz,
 *	1 channel, 3140928 bytes/channel
 *	Total Size: 1 * 3140928 + 4 (header) = 3140972 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/Scifi.wav
 *	Time-stamp: Mon Apr 15 10:32:18 2019
 *	
 **************************************************************/

#ifndef __SCIFIH__
#define __SCIFIH__

#define SCIFIFREQ 11025
#define SCIFILEN 3140928

extern const unsigned char Scifi[3140928];

#endif /* __SCIFIH__ */
