
/**************************************************************
 *	
 *	Tagirijus, 8 bit, 11025Hz,
 *	1 channel, 1087776 bytes/channel
 *	Total Size: 1 * 1087776 + 4 (header) = 1087820 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/Tagirijus.wav
 *	Time-stamp: Mon Apr 15 10:32:38 2019
 *	
 **************************************************************/

#ifndef __TAGIRIJUSH__
#define __TAGIRIJUSH__

#define TAGIRIJUSFREQ 11025
#define TAGIRIJUSLEN 1087776

extern const unsigned char Tagirijus[1087776];

#endif /* __TAGIRIJUSH__ */
