
/**************************************************************
 *	
 *	VangIsSomewhatIntenseAtTimes, 8 bit, 11025Hz,
 *	1 channel, 654624 bytes/channel
 *	Total Size: 1 * 654624 + 4 (header) = 654668 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/Final/ZZSources/AudioEdited/VangIsSomewhatIntenseAtTimes.wav
 *	Time-stamp: Fri Apr 19 18:07:26 2019
 *	
 **************************************************************/

#ifndef __VANGISSOMEWHATINTENSEATTIMESH__
#define __VANGISSOMEWHATINTENSEATTIMESH__

#define VANGISSOMEWHATINTENSEATTIMESFREQ 11025
#define VANGISSOMEWHATINTENSEATTIMESLEN 654624

extern const unsigned char VangIsSomewhatIntenseAtTimes[654624];

#endif /* __VANGISSOMEWHATINTENSEATTIMESH__ */
