
/**************************************************************
 *	
 *	VangReset, 8 bit, 11025Hz,
 *	1 channel, 11231 bytes/channel
 *	Total Size: 1 * 11231 + 4 (header) = 11275 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/VangReset.wav
 *	Time-stamp: Mon Apr 15 10:33:07 2019
 *	
 **************************************************************/

#ifndef __VANGRESETH__
#define __VANGRESETH__

#define VANGRESETFREQ 11025
#define VANGRESETLEN 11231

extern const unsigned char VangReset[11231];

#endif /* __VANGRESETH__ */
