
/**************************************************************
 *
 *	WinSound, 8 bit, 11025Hz,
 *	1 channel, 10937 bytes/channel
 *	Total Size: 1 * 10937 + 4 (header) = 10981 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Joeysaurus/Desktop/CS2261-A/FinalProject/M04/ZZSources/AudioEdited/WinSound.wav
 *	Time-stamp: Mon Apr 15 10:33:20 2019
 *
 **************************************************************/

#ifndef __WINSOUNDH__
#define __WINSOUNDH__

#define WINSOUNDFREQ 11025
#define WINSOUNDLEN 10937

extern const unsigned char WinSound[10937];

#endif /* __WINSOUNDH__ */
